version: '2'
services:

  r1ch1:
    scale: 1
    start_on_create: true
    health_check:
      port: 9000
      interval: 30000
      initializing_timeout: 10000
      reinitializing_timeout: 10000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  r1ch2:
    scale: 1
    start_on_create: true
    health_check:
      port: 9000
      interval: 30000
      initializing_timeout: 10000
      reinitializing_timeout: 10000
      unhealthy_threshold: 3
      strategy: none
      healthy_threshold: 2
      response_timeout: 2000

  client:
    scale: 1
    start_on_create: true
